stereo_camera_pub:
  ros__parameters:

    video_path: /home/opumechat/colcon_ws/videos/20200218_105527_0_115.avi
    #video_path: /home/opumechat/devel/depthai-df/build/move300_v100a100_trush.mp4
    enable_camera: false
    pub_from_image: false
    camera_num: 0
    image_path: /home/bkmn/colcon_ws/images/masked/
    is_grayscale: false

    fps: 5

    frame_id: davinci
    Camera_fx: 5.2569061657511509e+02
    Camera_fy: 5.2569061657511509e+02
    Camera_cx: 4.6150557447981282e+02
    Camera_cy: 2.7409307532556096e+02
    #distCoeffsL
    Camera_k1: -3.4828776048595911e-02
    Camera_k2: 5.3255842474875789e-02
    Camera_p1: 0.0
    Camera_p2: 0.0
    Camera_p3: 0.0