stereo_camera_pub:
  ros__parameters:

    camera_num: 0
    enable_camera: false
    frame_id: davinci
    image_path: ' '
    pub_from_image: false
    video_path: /home/bkmn/colcon_ws/videos/IPSJ_test1.avi
    is_pub_mask: false
    mask_path: /home/bkmn/colcon_ws/videos/surgery_move_camera_and_tool/mask_video.avi
    is_params_file: true
    params_file_path: file:///home/bkmn/colcon_ws/src/orb_slam2davinchi/config/davinci_Xi.yaml
    #image_processing_params: none   #blur : processed blur 10 times, step : processed step blur 20 times
    fps: 10

    Camera_fx: 5.2569061657511509e+02
    Camera_fy: 5.2569061657511509e+02
    Camera_cx: 4.6150557447981282e+02
    Camera_cy: 2.7409307532556096e+02
    #distCoeffsL
    Camera_k1: -3.4828776048595911e-02
    Camera_k2: 5.3255842474875789e-02
    Camera_p1: 0.0
    Camera_p2: 0.0
    Camera_p3: 0.0

