stereo_camera_pub:
  ros__parameters:
    video_path: /home/opumechat/colcon_ws/videos/move500_v100a100.mp4
    enable_camera: false
    pub_from_image: false
    camera_num: 0
    image_path: /home/bkmn/colcon_ws/images/masked/
    is_grayscale: true

    fps: 5

    frame_id: depthai_stereo
    Camera_fx: 799.51181055
    Camera_fy: 799.51181055
    Camera_cx: 672.1467694
    Camera_cy: 385.47394832
    #distCoeffsL
    Camera_k1: 13.750572e-02
    Camera_k2: -59.688676e-02
    Camera_p1: 1.58356459e-03
    Camera_p2: 4.51362066e-04
    Camera_p3: 1.17764829e+00